#
## DEFINITION OF THE ARENA
#

world_origin_units: "LATLON" # {"UTM, "LATLON"}

world_origin_x: 47.397743
world_origin_y: 8.545594

safety_area:

  use_safety_area: true

  frame_name: "world_origin"

  # convex polygon CCW
  safety_area: [
    -50, -50,
    50,  -50,
    50,  50,
    -50, 50
  ]

  max_z: 15.0
  min_z: 0.5

  polygon_obstacles:
    enabled: false

  point_obstacles:
    enabled: false
